name: egm722
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - geopandas
  - cartopy
  - notebook
  - rasterio
  - pyepsg
  - folium
  - python
  - geopandas
  - cartopy>=0.21
  - notebook
  - rasterio
  - pyepsg
  - folium
